# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue Dec 29 12:27:55 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.groupBox)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_preassembly_start = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preassembly_start.sizePolicy().hasHeightForWidth())
        self.pushButton_preassembly_start.setSizePolicy(sizePolicy)
        self.pushButton_preassembly_start.setAutoFillBackground(False)
        self.pushButton_preassembly_start.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);\n"
""))
        self.pushButton_preassembly_start.setObjectName(_fromUtf8("pushButton_preassembly_start"))
        self.verticalLayout_4.addWidget(self.pushButton_preassembly_start)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.pushButton_preassembly_next1 = QtGui.QPushButton(self.page_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preassembly_next1.sizePolicy().hasHeightForWidth())
        self.pushButton_preassembly_next1.setSizePolicy(sizePolicy)
        self.pushButton_preassembly_next1.setObjectName(_fromUtf8("pushButton_preassembly_next1"))
        self.verticalLayout_5.addWidget(self.pushButton_preassembly_next1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem2 = QtGui.QSpacerItem(20, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.label_3 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        spacerItem3 = QtGui.QSpacerItem(20, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.pushButton_preassembly_next2 = QtGui.QPushButton(self.page_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preassembly_next2.sizePolicy().hasHeightForWidth())
        self.pushButton_preassembly_next2.setSizePolicy(sizePolicy)
        self.pushButton_preassembly_next2.setObjectName(_fromUtf8("pushButton_preassembly_next2"))
        self.verticalLayout_6.addWidget(self.pushButton_preassembly_next2)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        spacerItem4 = QtGui.QSpacerItem(20, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.label_4 = QtGui.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_7.addWidget(self.label_4)
        spacerItem5 = QtGui.QSpacerItem(20, 88, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.pushButton_preassembly_next3 = QtGui.QPushButton(self.page_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preassembly_next3.sizePolicy().hasHeightForWidth())
        self.pushButton_preassembly_next3.setSizePolicy(sizePolicy)
        self.pushButton_preassembly_next3.setObjectName(_fromUtf8("pushButton_preassembly_next3"))
        self.verticalLayout_7.addWidget(self.pushButton_preassembly_next3)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_5 = QtGui.QLabel(self.page_5)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_8.addWidget(self.label_5)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtGui.QWidget()
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.page_6)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_6 = QtGui.QLabel(self.page_6)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_9.addWidget(self.label_6)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.page_7)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_7 = QtGui.QLabel(self.page_7)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_10.addWidget(self.label_7)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtGui.QWidget()
        self.page_8.setObjectName(_fromUtf8("page_8"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.page_8)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_8 = QtGui.QLabel(self.page_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_11.addWidget(self.label_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalSlider_x = QtGui.QSlider(self.page_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_x.sizePolicy().hasHeightForWidth())
        self.verticalSlider_x.setSizePolicy(sizePolicy)
        self.verticalSlider_x.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_x.setObjectName(_fromUtf8("verticalSlider_x"))
        self.horizontalLayout_2.addWidget(self.verticalSlider_x)
        self.verticalSlider_y = QtGui.QSlider(self.page_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_y.sizePolicy().hasHeightForWidth())
        self.verticalSlider_y.setSizePolicy(sizePolicy)
        self.verticalSlider_y.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_y.setObjectName(_fromUtf8("verticalSlider_y"))
        self.horizontalLayout_2.addWidget(self.verticalSlider_y)
        self.verticalSlider_z = QtGui.QSlider(self.page_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalSlider_z.sizePolicy().hasHeightForWidth())
        self.verticalSlider_z.setSizePolicy(sizePolicy)
        self.verticalSlider_z.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_z.setObjectName(_fromUtf8("verticalSlider_z"))
        self.horizontalLayout_2.addWidget(self.verticalSlider_z)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.pushButton_preassembly_next4 = QtGui.QPushButton(self.page_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preassembly_next4.sizePolicy().hasHeightForWidth())
        self.pushButton_preassembly_next4.setSizePolicy(sizePolicy)
        self.pushButton_preassembly_next4.setObjectName(_fromUtf8("pushButton_preassembly_next4"))
        self.verticalLayout_11.addWidget(self.pushButton_preassembly_next4)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtGui.QWidget()
        self.page_9.setObjectName(_fromUtf8("page_9"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_9)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_9 = QtGui.QLabel(self.page_9)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_12.addWidget(self.label_9)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem6)
        self.pushButton_preassembly_next5 = QtGui.QPushButton(self.page_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preassembly_next5.sizePolicy().hasHeightForWidth())
        self.pushButton_preassembly_next5.setSizePolicy(sizePolicy)
        self.pushButton_preassembly_next5.setObjectName(_fromUtf8("pushButton_preassembly_next5"))
        self.verticalLayout_12.addWidget(self.pushButton_preassembly_next5)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtGui.QWidget()
        self.page_10.setObjectName(_fromUtf8("page_10"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.page_10)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem7)
        self.label_10 = QtGui.QLabel(self.page_10)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_13.addWidget(self.label_10)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem8)
        self.pushButton_preassembly_next6 = QtGui.QPushButton(self.page_10)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preassembly_next6.sizePolicy().hasHeightForWidth())
        self.pushButton_preassembly_next6.setSizePolicy(sizePolicy)
        self.pushButton_preassembly_next6.setObjectName(_fromUtf8("pushButton_preassembly_next6"))
        self.verticalLayout_13.addWidget(self.pushButton_preassembly_next6)
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtGui.QWidget()
        self.page_11.setObjectName(_fromUtf8("page_11"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.page_11)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.pushButton_beep = QtGui.QPushButton(self.page_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_beep.sizePolicy().hasHeightForWidth())
        self.pushButton_beep.setSizePolicy(sizePolicy)
        self.pushButton_beep.setObjectName(_fromUtf8("pushButton_beep"))
        self.verticalLayout_14.addWidget(self.pushButton_beep)
        self.pushButton_preassembly_finish = QtGui.QPushButton(self.page_11)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_preassembly_finish.sizePolicy().hasHeightForWidth())
        self.pushButton_preassembly_finish.setSizePolicy(sizePolicy)
        self.pushButton_preassembly_finish.setObjectName(_fromUtf8("pushButton_preassembly_finish"))
        self.verticalLayout_14.addWidget(self.pushButton_preassembly_finish)
        self.stackedWidget.addWidget(self.page_11)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.pushButton_preassembly_reset = QtGui.QPushButton(self.groupBox)
        self.pushButton_preassembly_reset.setObjectName(_fromUtf8("pushButton_preassembly_reset"))
        self.verticalLayout.addWidget(self.pushButton_preassembly_reset)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.pushButton_getid = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_getid.sizePolicy().hasHeightForWidth())
        self.pushButton_getid.setSizePolicy(sizePolicy)
        self.pushButton_getid.setObjectName(_fromUtf8("pushButton_getid"))
        self.verticalLayout_2.addWidget(self.pushButton_getid)
        self.pushButton_setid = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_setid.sizePolicy().hasHeightForWidth())
        self.pushButton_setid.setSizePolicy(sizePolicy)
        self.pushButton_setid.setObjectName(_fromUtf8("pushButton_setid"))
        self.verticalLayout_2.addWidget(self.pushButton_setid)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setStyleSheet(_fromUtf8("\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.pushButton_postassembly_start = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_postassembly_start.sizePolicy().hasHeightForWidth())
        self.pushButton_postassembly_start.setSizePolicy(sizePolicy)
        self.pushButton_postassembly_start.setObjectName(_fromUtf8("pushButton_postassembly_start"))
        self.verticalLayout_3.addWidget(self.pushButton_postassembly_start)
        self.horizontalLayout.addWidget(self.groupBox_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Preassembly Test", None))
        self.pushButton_preassembly_start.setText(_translate("MainWindow", "Start", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>LED: <span style=\" color:#ff0004;\">Red</span></p></body></html>", None))
        self.pushButton_preassembly_next1.setText(_translate("MainWindow", "Next", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>LED: <span style=\" color:#00aa00;\">Green</span></p></body></html>", None))
        self.pushButton_preassembly_next2.setText(_translate("MainWindow", "Next", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>LED: <span style=\" color:#0000ff;\">Blue</span></p></body></html>", None))
        self.pushButton_preassembly_next3.setText(_translate("MainWindow", "Next", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Press the <span style=\" font-weight:600;\">power</span> button to continue</p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Press the <span style=\" font-weight:600;\">&quot;A&quot;</span> button to continue</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Press the <span style=\" font-weight:600;\">&quot;B&quot;</span> button to continue</p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "Accelerometer Test:", None))
        self.pushButton_preassembly_next4.setText(_translate("MainWindow", "Next", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Make sure the motors are moving <span style=\" font-weight:600;\">counter-clockwise</span>.</p></body></html>", None))
        self.pushButton_preassembly_next5.setText(_translate("MainWindow", "Next", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Make sure the motors are moving <span style=\" font-weight:600;\">clockwise</span>.</p></body></html>", None))
        self.pushButton_preassembly_next6.setText(_translate("MainWindow", "Next", None))
        self.pushButton_beep.setText(_translate("MainWindow", "Beep!", None))
        self.pushButton_preassembly_finish.setText(_translate("MainWindow", "Finish", None))
        self.pushButton_preassembly_reset.setText(_translate("MainWindow", "Reset", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Serial ID", None))
        self.pushButton_getid.setText(_translate("MainWindow", "Get ID", None))
        self.pushButton_setid.setText(_translate("MainWindow", "Set ID", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Postassembly Test", None))
        self.label.setText(_translate("MainWindow", "Ready", None))
        self.pushButton_postassembly_start.setText(_translate("MainWindow", "Start", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

